export const imageCarousel = [
  {
    image: require("./assets/bitcoinn.png"),
    desc: "Blockchain",
  },
  {
    image: require("./assets/lisk.png"),
    desc: "Cryptocurrency",
  },
  {
    image: require("./assets/web.png"),
    desc: "Web development",
  },
  {
    image: require("./assets/web3.png"),
    desc: "Web3",
  },
  {
    image: require("./assets/figma.png"),
    desc: "UI/UX Design",
  },
  {
    image: require("./assets/candle.png"),
    desc: "Crypto Trading",
  },
  
];

export const courseCategories = [
  {
    category: "All",
  },
  {
    category: "Business",
  },
  {
    category: "Marketing",
  },
  {
    category: "Development",
  },
  {
    category: "Design",
  },
  {
    category: "Cryptocurrency",
  },
  
];

export const courses = [
  {
    image: require("./assets/img.png"),
    title: "Development",
    starIcon: "ri-star-s-fill",
    rating: "4.8",
    desc: "Java, html, c++ and css beginner to pro masterclass",
    authorImg: require("./assets/avatar.png"),
    name: "Ronald Richards",
    price: "0.000017 ETH",
    clockIcon: "ri-time-line",
    bookIcon: "ri-book-3-line",
    groupIcon: "ri-group-line",
    time: "3hr 30min",
    para: "10 Lessons",
    number: "112,290",
    rate: "Bestseller",
    heartIcon: "ri-heart-3-fill",
  },
  {
    image: require("./assets/learning.png"),
    title: "Development",
    starIcon: "ri-star-s-fill",
    rating: "4.8",
    desc: "Java, html, c++ and css beginner to pro masterclass",
    authorImg: require("./assets/avatar.png"),
    name: "Ronald Richards",
    price: "0.000017 ETH",
    clockIcon: "ri-time-line",
    bookIcon: "ri-book-3-line",
    groupIcon: "ri-group-line",
    time: "3hr 30min",
    para: "10 Lessons",
    number: "112,290",
    rate: "Bestseller",
    heartIcon: "ri-heart-3-fill",
  },
  {
    image: require("./assets/forex.png"),
    title: "Development",
    starIcon: "ri-star-s-fill",
    rating: "4.8",
    desc: "Java, html, c++ and css beginner to pro masterclass",
    authorImg: require("./assets/avatar.png"),
    name: "Ronald Richards",
    price: "0.000017 ETH",
    clockIcon: "ri-time-line",
    bookIcon: "ri-book-3-line",
    groupIcon: "ri-group-line",
    time: "3hr 30min",
    para: "10 Lessons",
    number: "112,290",
    rate: "Bestseller",
    heartIcon: "ri-heart-3-fill",
  },
  {
    image: require("./assets/img.png"),
    title: "Development",
    starIcon: "ri-star-s-fill",
    rating: "4.8",
    desc: "Java, html, c++ and css beginner to pro masterclass",
    authorImg: require("./assets/avatar.png"),
    name: "Ronald Richards",
    price: "0.000017 ETH",
    clockIcon: "ri-time-line",
    bookIcon: "ri-book-3-line",
    groupIcon: "ri-group-line",
    time: "3hr 30min",
    para: "10 Lessons",
    number: "112,290",
    rate: "Bestseller",
    heartIcon: "ri-heart-3-fill",
  },
  {
    image: require("./assets/img.png"),
    title: "Development",
    starIcon: "ri-star-s-fill",
    rating: "4.8",
    desc: "Java, html, c++ and css beginner to pro masterclass",
    authorImg: require("./assets/avatar.png"),
    name: "Ronald Richards",
    price: "0.000017 ETH",
    clockIcon: "ri-time-line",
    bookIcon: "ri-book-3-line",
    groupIcon: "ri-group-line",
    time: "3hr 30min",
    para: "10 Lessons",
    number: "112,290",
    rate: "Bestseller",
    heartIcon: "ri-heart-3-fill",
  },
  {
    image: require("./assets/img.png"),
    title: "Development",
    starIcon: "ri-star-s-fill",
    rating: "4.8",
    desc: "Java, html, c++ and css beginner to pro masterclass",
    authorImg: require("./assets/avatar.png"),
    name: "Ronald Richards",
    price: "0.000017 ETH",
    clockIcon: "ri-time-line",
    bookIcon: "ri-book-3-line",
    groupIcon: "ri-group-line",
    time: "3hr 30min",
    para: "10 Lessons",
    number: "112,290",
    rate: "Bestseller",
    heartIcon: "ri-heart-3-fill",
  },
];
